### ISSUE TITLE
 最新的 报错

### ISSUE THREAD

**Issue by pbwei** [xsbear/vue-webpack4-babel7#2]
laster

 building for production...(node:13684) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: "dependency" is not a valid chunk sort mode
(node:13684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xsbear** [comment]
无法重现。请检查node是否升级到较新版本，如8.0以上，然后考虑删除node_modules重新安装依赖
